docs: add contributing guidelines
desmos-labs/desmos-contracts pull request #109
Opened 2022-10-18 13:23 UTC by manu0466

This PR adds a `CONTRIBUTING.md` file with the contributing guidelines and the templates to open new issues and PRs

2022-10-19 08:03 UTC, dadamu approved these changes
LGTM

2022-10-19 08:05 UTC, dadamu commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] targeted the correct branch (see [PR Targeting](https://github.com/desmos-labs/desmos/blob/master/CONTRIBUTING.md#pr-targeting))
```suggestion
- [ ] targeted the correct branch (see [PR Targeting](https://github.com/desmos-labs/desmos-contracts/blob/master/CONTRIBUTING.md#pr-targeting))
```
It should target to this repo.

2022-10-19 08:06 UTC, dadamu commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] followed the guidelines for [building modules](https://docs.cosmos.network/v0.44/building-modules/intro.html)
```suggestion
```
It can be removed since the contract would not include modules.

2022-10-19 08:07 UTC, dadamu commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] included the necessary unit and integration [tests](https://github.com/desmos-labs/desmos/blob/master/CONTRIBUTING.md#testing)
```suggestion
- [ ] included the necessary unit and integration [tests](https://github.com/desmos-labs/desmos-contracts/blob/master/CONTRIBUTING.md#testing)
```

2022-10-19 08:08 UTC, dadamu requested changes
Overall is good to me, just some minor things can be improved.

2022-10-19 15:16 UTC, bragaz approved these changes

2022-10-20 03:51 UTC, dadamu approved these changes

2022-10-20 03:52 UTC, merged